name: PR Semver Labeling
on:
  workflow_call:
    inputs:
      semver_labels:
        required: true
        type: string
        default: '{"majorLabel": "major-release","minorLabel": "minor-release", "patchLabel": "patch-release"}'
      repository:
        required: true
        type: string
      pr_number:
        required: true
        type: string
    outputs:
      label_to_apply:
        description: "The label to apply"
        value: ${{ jobs.check-pr-title.outputs.label_to_apply }}
      found_match:
        description: "Whether a semver match was found"
        value: ${{ jobs.check-pr-title.outputs.found_match }}

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @actions/github @actions/core --force

      - name: Check PR title for semver
        id: check_version
        run: node functions/check-semver.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMVER_LABELS: ${{ inputs.semver_labels }}

      - name: Check Outputs
        run: |
          echo ${{ steps.check_version.outputs.found_match }}
          echo ${{ steps.check_version.outputs.label_to_apply }}

      - name: Label PR
        if: steps.check_version.outputs.found_match == 'true'
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ inputs.repository }}
          NUMBER: ${{ inputs.pr_number }}
          LABELS: "${{ steps.check_version.outputs.label_to_apply }}"
