name: 'PR Semver Labeler'
description: 'Add a label to PRs based on semver in title'
inputs:
  token:
    description: 'GitHub token'
    required: true
  labels:
    description: 'JSON string of labels'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
  pre: 'npm install'
