name: 'PR Semver Labeler'
description: 'Add a label to PRs based on semver in title'
author: 'JKBeeman92'
branding:
  color: 'green'
  icon: 'arrow-up'
inputs:
  token:
    description: 'GitHub token'
    required: true
  semver_labels:
    description: 'JSON string of labels'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
